#!/usr/bin/env python3
"""
Headless Browser Authentication Helper.

Uses Playwright/Chromium to authenticate via JavaScript-rendered login pages.
Exports session cookies to a Netscape cookie jar file for use with curl.

Usage:
    python3 browser-auth.py \\
        --url https://app.example.com/login \\
        --username user@example.com \\
        --password secret123 \\
        --cookie-jar ./engagements/<eid>/cookies.txt \\
        [--username-selector 'input[name="username"]'] \\
        [--password-selector 'input[name="password"]'] \\
        [--submit-selector 'button[type="submit"]'] \\
        [--wait-for-url '**/dashboard*'] \\
        [--timeout 30000]
"""

import argparse
import sys
import time


def cookies_to_netscape(cookies, filepath):
    """Write cookies to Netscape cookie jar format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by browser-auth.py",
        "",
    ]
    for cookie in cookies:
        domain = cookie.get("domain", "")
        if not domain.startswith("."):
            domain = "." + domain
        http_only = "TRUE" if cookie.get("httpOnly", False) else "FALSE"
        path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        expires = str(int(cookie.get("expires", 0)))
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        lines.append(
            f"{domain}\t{http_only}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
        )

    with open(filepath, "w") as f:
        f.write("\n".join(lines) + "\n")


def extract_bearer_token(page):
    """Try to extract Bearer token from localStorage/sessionStorage."""
    token = None
    for storage_type in ["localStorage", "sessionStorage"]:
        for key_pattern in [
            "token",
            "access_token",
            "accessToken",
            "auth_token",
            "authToken",
            "kc-callback",
        ]:
            try:
                value = page.evaluate(
                    f"""() => {{
                    for (let i = 0; i < {storage_type}.length; i++) {{
                        const key = {storage_type}.key(i);
                        if (key.toLowerCase().includes('{key_pattern.lower()}')) {{
                            const val = {storage_type}.getItem(key);
                            try {{ return JSON.parse(val); }} catch {{ return val; }}
                        }}
                    }}
                    return null;
                }}"""
                )
                if value:
                    if isinstance(value, dict) and "access_token" in value:
                        token = value["access_token"]
                    elif isinstance(value, dict) and "token" in value:
                        token = value["token"]
                    elif isinstance(value, str) and len(value) > 20:
                        token = value
                    if token:
                        return token
            except Exception:
                continue
    return token


def main():
    parser = argparse.ArgumentParser(
        description="Headless Browser Auth Helper",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic Keycloak login
  python3 browser-auth.py --url https://app.example.com/login \\
    --username user@example.com --password secret \\
    --cookie-jar ./cookies.txt

  # Custom selectors for non-standard forms
  python3 browser-auth.py --url https://app.example.com/login \\
    --username user@example.com --password secret \\
    --username-selector '#email' --password-selector '#pass' \\
    --submit-selector '.login-btn' --cookie-jar ./cookies.txt
        """,
    )
    parser.add_argument("--url", required=True, help="Login page URL")
    parser.add_argument("--username", required=True, help="Username or email")
    parser.add_argument("--password", required=True, help="Password")
    parser.add_argument("--cookie-jar", required=True, help="Output cookie jar path")
    parser.add_argument(
        "--username-selector",
        default='input[name="username"], input[type="email"], input[id="username"], #username, input[name="email"]',
        help="CSS selector for username field",
    )
    parser.add_argument(
        "--password-selector",
        default='input[name="password"], input[type="password"], input[id="password"], #password',
        help="CSS selector for password field",
    )
    parser.add_argument(
        "--submit-selector",
        default='button[type="submit"], input[type="submit"], #kc-login, .submit-button, button.pf-c-button',
        help="CSS selector for submit button",
    )
    parser.add_argument(
        "--wait-for-url",
        help="URL pattern to wait for after login (glob pattern, e.g. '**/dashboard*')",
    )
    parser.add_argument(
        "--timeout", type=int, default=30000, help="Timeout in ms (default: 30000)"
    )
    parser.add_argument(
        "--screenshot-on-failure",
        default="/tmp/auth-failure.png",
        help="Screenshot path on failure (default: /tmp/auth-failure.png)",
    )
    parser.add_argument(
        "--extract-token",
        action="store_true",
        help="Also extract Bearer token from browser storage",
    )
    parser.add_argument(
        "--profile",
        default=None,
        help="Isolated browser profile directory for session isolation. "
             "Each subagent should use a unique profile to prevent cookie/session conflicts "
             "(e.g., ./engagements/<eid>/browser-profiles/agent-1)",
    )
    args = parser.parse_args()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "[-] Playwright not installed. Run: pip install playwright && playwright install chromium",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"[*] Opening headless browser to: {args.url}", file=sys.stderr)

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--ignore-certificate-errors",
                "--disable-web-security",
            ],
        )
        # Use isolated profile if specified (for parallel subagent session isolation)
        context_kwargs = {"ignore_https_errors": True}
        if args.profile:
            import os
            os.makedirs(args.profile, exist_ok=True)
            state_file = os.path.join(args.profile, "state.json")
            if os.path.exists(state_file):
                context_kwargs["storage_state"] = state_file
                print(f"    Restoring browser state from: {state_file}", file=sys.stderr)

        context = browser.new_context(**context_kwargs)
        page = context.new_page()

        try:
            # Navigate to login page
            page.goto(args.url, wait_until="networkidle", timeout=args.timeout)
            print(f"    Page loaded: {page.url}", file=sys.stderr)
            print(f"    Title: {page.title()}", file=sys.stderr)

            # Wait for username field to be visible
            username_el = None
            for selector in args.username_selector.split(", "):
                selector = selector.strip()
                try:
                    el = page.wait_for_selector(selector, timeout=5000)
                    if el and el.is_visible():
                        username_el = el
                        print(f"    Username field found: {selector}", file=sys.stderr)
                        break
                except Exception:
                    continue

            if not username_el:
                print(
                    "[-] Could not find username field with any known selector",
                    file=sys.stderr,
                )
                page.screenshot(path=args.screenshot_on_failure)
                print(
                    f"    Screenshot saved to: {args.screenshot_on_failure}",
                    file=sys.stderr,
                )
                sys.exit(1)

            # Find password field
            password_el = None
            for selector in args.password_selector.split(", "):
                selector = selector.strip()
                try:
                    el = page.query_selector(selector)
                    if el and el.is_visible():
                        password_el = el
                        print(f"    Password field found: {selector}", file=sys.stderr)
                        break
                except Exception:
                    continue

            if not password_el:
                print(
                    "[-] Could not find password field with any known selector",
                    file=sys.stderr,
                )
                page.screenshot(path=args.screenshot_on_failure)
                sys.exit(1)

            # Fill credentials
            username_el.fill(args.username)
            password_el.fill(args.password)

            # Find and click submit button
            print("[*] Submitting credentials...", file=sys.stderr)
            submit_el = None
            for selector in args.submit_selector.split(", "):
                selector = selector.strip()
                try:
                    el = page.query_selector(selector)
                    if el and el.is_visible():
                        submit_el = el
                        print(f"    Submit button found: {selector}", file=sys.stderr)
                        break
                except Exception:
                    continue

            if submit_el:
                submit_el.click()
            else:
                # Fallback: press Enter on password field
                print(
                    "    No submit button found, pressing Enter", file=sys.stderr
                )
                password_el.press("Enter")

            # Wait for navigation
            if args.wait_for_url:
                page.wait_for_url(args.wait_for_url, timeout=args.timeout)
            else:
                page.wait_for_load_state("networkidle", timeout=args.timeout)
                # Extra time for redirects to complete
                time.sleep(3)

            final_url = page.url
            print(f"    Post-login URL: {final_url}", file=sys.stderr)

            # Check if we're still on the login page (auth failed)
            if "login" in final_url.lower() and "login" in args.url.lower():
                # Check for error messages
                error_text = page.evaluate(
                    """() => {
                    const el = document.querySelector('.alert-error, .error-message, #input-error, .kc-feedback-text');
                    return el ? el.textContent.trim() : null;
                }"""
                )
                if error_text:
                    print(
                        f"[-] Login failed: {error_text}", file=sys.stderr
                    )
                    page.screenshot(path=args.screenshot_on_failure)
                    sys.exit(1)

            # Get cookies from all domains
            cookies = context.cookies()
            print(f"    Captured {len(cookies)} cookies", file=sys.stderr)

            # Save to cookie jar
            cookies_to_netscape(cookies, args.cookie_jar)
            print(f"[+] Cookies saved to: {args.cookie_jar}", file=sys.stderr)

            # Save browser state for profile isolation
            if args.profile:
                state_file = os.path.join(args.profile, "state.json")
                context.storage_state(path=state_file)
                print(f"    Browser state saved to: {state_file}", file=sys.stderr)

            # Print cookies summary
            for c in cookies:
                val_preview = c["value"][:20] + "..." if len(c["value"]) > 20 else c["value"]
                print(
                    f"    {c['domain']}: {c['name']}={val_preview}",
                    file=sys.stderr,
                )

            # Extract Bearer token if requested
            if args.extract_token:
                token = extract_bearer_token(page)
                if token:
                    print("\n[+] Bearer token extracted:", file=sys.stderr)
                    print(token)
                else:
                    print(
                        "    No Bearer token found in browser storage",
                        file=sys.stderr,
                    )

        except Exception as e:
            print(f"[-] Browser auth failed: {e}", file=sys.stderr)
            try:
                page.screenshot(path=args.screenshot_on_failure)
                print(
                    f"    Screenshot saved to: {args.screenshot_on_failure}",
                    file=sys.stderr,
                )
            except Exception:
                pass
            sys.exit(1)
        finally:
            browser.close()


if __name__ == "__main__":
    main()
